version: '3.8'

services:
  web:
    image: ghcr.io/faizullin/uyren-courselit-my/web:${IMAGE_TAG:-latest}
    container_name: courselit-web-prod
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - courselit-prod-network

  queue:
    image: ghcr.io/faizullin/uyren-courselit-my/queue:${IMAGE_TAG:-latest}
    container_name: courselit-queue-prod
    ports:
      - "${QUEUE_PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - courselit-prod-network

  redis:
    image: redis
    container_name: courselit-redis-prod
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - courselit-prod-network

  mongodb:
    image: mongo
    container_name: courselit-mongo-prod
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-courselit}
    env_file:
      - .env.prod
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_DATABASE:-courselit} --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - courselit-prod-network

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local

networks:
  courselit-prod-network:
    name: courselit-prod-network
    driver: bridge
