name: Build and Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.4.1
        
    - name: Install and build
      run: |
        pnpm install --frozen-lockfile
        pnpm build
        
    - name: Build Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.web
        push: true
        tags: ghcr.io/${{ github.repository }}/web:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build queue image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.queue
        push: true
        tags: ghcr.io/${{ github.repository }}/queue:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /path/to/project
          git pull origin main
          cd docker
          docker-compose -f docker-compose.prod.yml --env-file .env.prod pull
          docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d
          docker system prune -f
